[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
disallow_untyped_decorators = false

[tool.isort]
profile = "black"
line_length = 120
force_single_line = true
force_sort_within_sections = true

[tool.black]
line-length = 120
target-version = ['py312']
skip-string-normalization = true
